### ISSUE TITLE
v1.57.0 fails with Java 8

### ISSUE THREAD

**Issue by bestbeforetoday** [grpc/grpc-java#10432]
### What version of gRPC-Java are you using?
1.57.0

### What is your environment?
- Java Temurin version 8.0.372+7
- Ubuntu 22.0.4 LTS

### What did you expect to see?
Remote gRPC service calls work.

### What did you see instead?
Code that ran perfectly with previous gRPC-Java versions now fails *only* on Java 8, with the following error:
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
```

The same code continues to run fine with Java 11 and Java 17. Failures only occur with Java 8 using v1.57.0 of gRPC-Java. Might this be a symptom of the published code being compiled with a later Java version without the compiler **release** option being correctly set to **8**, and so generating bytecode that refers to a method overload that does not exist in the Java 8 standard library?

Using a blocking stub, this is the error:
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at io.grpc.internal.MessageFramer.writeKnownLengthUncompressed(MessageFramer.java:225)
	at io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:169)
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:142)
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:66)
	at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)
	at io.grpc.internal.DelayedStream$6.run(DelayedStream.java:283)
	at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:182)
	at io.grpc.internal.DelayedStream.access$100(DelayedStream.java:44)
	at io.grpc.internal.DelayedStream$4.run(DelayedStream.java:148)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.runQuietly(ClientCalls.java:777)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:760)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:161)
```

Using a future stub, this is the error:
```
Exception in thread "grpc-default-executor-0" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at io.grpc.internal.MessageFramer.writeKnownLengthUncompressed(MessageFramer.java:225)
	at io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:169)
	at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:142)
	at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:66)
	at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)
	at io.grpc.internal.DelayedStream$6.run(DelayedStream.java:283)
	at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:182)
	at io.grpc.internal.DelayedStream.access$100(DelayedStream.java:44)
	at io.grpc.internal.DelayedStream$4.run(DelayedStream.java:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

### Steps to reproduce the bug
Invoke remote gRPC services.

**Comment by jrhee17** [comment]
+1 We're also seeing the same issue:

```java
GrpcServiceServerTest > reflectionService() FAILED
    java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at io.grpc.internal.MessageFramer.writeKnownLengthUncompressed(MessageFramer.java:225)
        at io.grpc.internal.MessageFramer.writeUncompressed(MessageFramer.java:169)
        at io.grpc.internal.MessageFramer.writePayload(MessageFramer.java:142)
        at io.grpc.internal.AbstractStream.writeMessage(AbstractStream.java:66)
        at io.grpc.internal.ForwardingClientStream.writeMessage(ForwardingClientStream.java:37)
        at io.grpc.internal.DelayedStream$6.run(DelayedStream.java:283)
        at io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:182)
        at io.grpc.internal.DelayedStream.access$100(DelayedStream.java:44)
        at io.grpc.internal.DelayedStream$4.run(DelayedStream.java:148)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

ref: https://github.com/line/armeria/actions/runs/5706739708/job/15462723107?pr=5086#step:7:1636

**Comment by ejona86** [comment]
This was probably caused by https://github.com/grpc/grpc-java/pull/10299 .

**Comment by ejona86** [comment]
(I think there's some open issue in AnimalSniffer where it fails to catch stuff like this.)

**Comment by ejona86** [comment]
In order to verify:
```
./gradlew :grpc-core:build
unzip core/build/libs/grpc-core-1.58.0-SNAPSHOT.jar io/grpc/internal/MessageFramer.class
javap -c -p io/grpc/internal/MessageFramer.class | grep 'java/nio/ByteBuffer.clear:'
```

We want to see `java/nio/ByteBuffer.clear:()Ljava/nio/Buffer;` (specifically the return type Buffer, not ByteBuffer).

**Comment by cpovirk** [comment]
> (I think there's some open issue in AnimalSniffer where it fails to catch stuff like this.)

https://github.com/grpc/grpc-java/issues/7360

(One day, I will have a conversation with you that is not prompted by a bug in a build tool :))

**Comment by ejona86** [comment]
I just sent out a fix. Not too scary. I verified that the ByteBuf.clear reference was correct in Java 8 and 11. And I also verified that io.grpc.Context remained using Java 7 bytecode. I also checked that Java 17 supports `--release 7`, but didn't actually do a build with it. That's important because in ~a month Java 11 no longer has active support and our build will probably need to move to Java 17.

@cpovirk, maybe some day, but likely not before Java 8 dies and JSpecify lands! (In related news, we need to fight the Gradle Module Metadata stuff with Guava 32.0.1! Don't be concerned yet; we still need to figure out which way is up.)

**Comment by Tallicia** [comment]
Thanks for addressing this! Quick quesiton, will this be backported to a 1.57.1 patch before the 1.58 release/milestone scheduled for 4 weeks from now(Aug 29)? If so, is there any rough timeline for a patch release?

**Comment by Tallicia** [comment]
I see a PR here, so woot woot! https://github.com/grpc/grpc-java/pull/10442

**Comment by ejona86** [comment]
I just released 1.57.1. It should show up on repo1.maven.org any minute now. Within an hour or two it'll probably be on your favorite mirror.

I don't know if search.maven.org changed their index frequency. Previously we'd expect it to be updated within a day. I don't know if the new UI also brought any backend changes to increase the index update frequency. But in any case, don't worry if it doesn't yet show up on search.maven.org, as your build can use it well before that point.

-------

On the positive side, this issue informed us 1) some users are updating to releases soon after their release (thanks! whether you update on a schedule or with automation) and 2) Java 8 is still reasonably well used by those users.

**Comment by Tallicia** [comment]
Thanks for this quick turnaround, the patch works as expected and the CVE issue is mitigated now. Great work! Side note, moving up from Java 8 is in our backlog.

**Comment by sergiitk** [comment]
For posterity, here's how @ejona86's change affected `io/grpc/internal/MessageFramer.class`

- io/grpc/internal/MessageFramer.class.1.txt - before
- io/grpc/internal/MessageFramer.class.2.txt - after

```diff
--- io/grpc/internal/MessageFramer.class.1.txt	2023-08-02 11:36:18
+++ io/grpc/internal/MessageFramer.class.2.txt	2023-08-02 11:36:28
@@ -407,7 +407,7 @@
       53: athrow
       54: aload_0
       55: getfield      #13                 // Field headerScratch:Ljava/nio/ByteBuffer;
-      58: invokevirtual #63                 // Method java/nio/ByteBuffer.clear:()Ljava/nio/ByteBuffer;
+      58: invokevirtual #63                 // Method java/nio/ByteBuffer.clear:()Ljava/nio/Buffer;
       61: pop
       62: aload_0
       63: getfield      #13                 // Field headerScratch:Ljava/nio/ByteBuffer;
@@ -451,7 +451,7 @@
        4: istore_3
        5: aload_0
        6: getfield      #13                 // Field headerScratch:Ljava/nio/ByteBuffer;
-       9: invokevirtual #63                 // Method java/nio/ByteBuffer.clear:()Ljava/nio/ByteBuffer;
+       9: invokevirtual #63                 // Method java/nio/ByteBuffer.clear:()Ljava/nio/Buffer;
       12: pop
       13: aload_0
       14: getfield      #13                 // Field headerScratch:Ljava/nio/ByteBuffer;
```
