### ISSUE TITLE
Cannot find a symbol GrpcGenerated after upgrade to 1.40.x

### ISSUE THREAD

**Issue by luankevinferreira** [grpc/grpc-java#8523]
### What version of gRPC-Java are you using?
1.40.1

### What is your environment?

Mac OS, Open JDK 11

### What did you expect to see?
Compilation success

### What did you see instead?

cannot find symbol
[ERROR]   symbol:   class GrpcGenerated
[ERROR]   location: package io.grpc.stub.annotations

### Steps to reproduce the bug

I'm using the following plugin to generate classes, but when I upgrade to the mentioned version, the error occurs.

P.S.: with 1.39.0 the error did not occur.

```xml
                         <plugin>
				<groupId>org.xolstice.maven.plugins</groupId>
				<artifactId>protobuf-maven-plugin</artifactId>
				<version>${protobuf-maven-plugin.version}</version>
				<configuration>
					<protocArtifact>
						com.google.protobuf:protoc:3.17.3:exe:${os.detected.classifier}
					</protocArtifact>
					<pluginId>grpc-java</pluginId>
					<pluginArtifact>
						io.grpc:protoc-gen-grpc-java:1.39.0:exe:${os.detected.classifier}
					</pluginArtifact>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>compile</goal>
							<goal>compile-custom</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

**Comment by dapengzhang0** [comment]
The `GrpcGenerated` class is introduced in v1.40. If you generate the stub classes with the plugin io.grpc:protoc-gen-grpc-java:1.40.1, they will contain `GrpcGenerated`, and you must also use grpc v1.40.1 for your client, e.g.:

```
<dependency>
    <groupId>io.grpc</groupId>
    <artifactId>grpc-stub</artifactId>
    <version>1.40.1</version>
</dependency>
```

**Comment by luankevinferreira** [comment]
Thank you @dapengzhang0 for the comment, I'm using https://github.com/yidongnan/grpc-spring-boot-starter and I see that they are using the grpc version `1.37.0` https://github.com/yidongnan/grpc-spring-boot-starter/blob/master/build.gradle#L15
