### ISSUE TITLE
Dependency upgrades

### ISSUE THREAD

**Issue by elharo** [grpc/grpc-java#4700]
In build.gradle

google_api_protos: 'com.google.api.grpc:proto-google-common-protos:1.0.0' --> 1.12.0
com.google.auth:google-auth-library-credentials:0.9.0 to 0.9.1
com.google.code.findbugs:jsr305:3.0.0 to 3.0.2
protobufVersion 3.5.1 --> 3.6.0

There may be others but these are the ones that are conflicting upstream (that is, other versions already being selected) in google-cloud-java

**Comment by carl-mastrangelo** [comment]
@elharo We can't do the protobuf one because we are still stuck on Java6, and proto requires Java7.  I can see about testing the JSR 305 internally, but cannot comment on the auth library.  Perhaps @ejona86  can say more.

**Comment by ejona86** [comment]
Note that #4680 would reduce the need for issues like this, as we could regularly bump all versions.

It looks like proto-google-common-protos is broken, in that it doesn't include the .proto files any more.

We definitely want google-auth-library-credentials bump. It adds JWT caching. It's disappointing we didn't do that earlier. Note that we should actually bump to 0.10.0, not 0.9.1.

jsr305 bump seems like it'd be fine.

A week or so after 1.14.0 release we can drop support of Java 6 and bump the version of protobuf. We can also bump Guava at the same time.

**Comment by elharo** [comment]
@ejona86 Is this the breakage you're referring to? I just saw this at head. If so,  I guess that's a separate issue to fix?

```
> Task :grpc-compiler:compileJava_pluginExecutableJava_pluginCpp
In file included from /Users/elharo/grpc-java/compiler/src/java_plugin/cpp/java_plugin.cpp:8:
/Users/elharo/grpc-java/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

/Users/elharo/grpc-java/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

In file included from /Users/elharo/grpc-java/compiler/src/java_plugin/cpp/java_generator.cpp:1:
/Users/elharo/grpc-java/compiler/src/java_plugin/cpp/java_generator.h:8:10: fatal error: 'google/protobuf/io/zero_copy_stream.h' file not found
#include <google/protobuf/io/zero_copy_stream.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by ejona86** [comment]
@elharo, no that's not I was referring to. That's a problem with 1) not having protobuf headers available or 2) having too old a version of protobuf. The problem I was talking about would impact running codegen for .proto files that depend on the generated code in proto-google-common-protos, not compiling codegen.

@patflynn, right now we're just biding our time for a few more people to notice the announcement of dropping Java 6 support that we're going to include in the release today. But #3961 is really the place for discussion on dropping support of Java 6. #4671 is for dropping Java 7.

**Comment by elharo** [comment]
Filed #4715 for the proto issue

**Comment by zxtwonder** [comment]
A question about protobuf version - Can grpc-java work with protobuf 3.6.0 currently after overriding dependency? And what is the current plan to officially move to protobuf 3.6.0+?

We have a mixed dependency on protobuf and grpc in C++ and Java. Currently we downgrade to protobuf 3.5.1 across the board to generate universal proto C++ files to accommodate grpc-java.

**Comment by ejona86** [comment]
grpc-java works with 3.6.0. grpc-java should always work with newer minor/patch versions of dependencies... except for Netty (which is why we have grpc-netty-shaded).

v1.15.0 dropped Java 6 support, and it didn't have any fallout. So starting in v1.16 we could have upgraded the protobuf dependency fairly safely. We just got side-tracked with other things and didn't. It would be nice to do for v1.17...

**Comment by elharo** [comment]
Maybe for 1.19 we can upgrade protobuf?

**Comment by elharo** [comment]
Looks like it's done in build.gradle. Think I saw an example file somewhere that still used the old version though. Searching...

**Comment by elharo** [comment]
all of these are done except google-auth-library-credentials

**Comment by ejona86** [comment]
@elharo, it looks like 0.13.0 is out. That's probably what we'd upgrade to.
