### PR TITLE
android-interop-testing: align AndroidX Test Runner version to 1.7.0

### PR DESCRIPTION
**Pull request by shivaspeaks**
Fixes android failure discussed in https://github.com/grpc/grpc-java/pull/12689#issuecomment-4067946540

### CODE REVIEW

**Review by ejona86 — APPROVED** [review]

**Comment by shivaspeaks** [comment]
We are seeing a new error now:
https://firebase.corp.google.com/u/0/project/grpc-testing/testlab/histories/bh.6e2cfdde264f9eb3/matrices/8610605656647595667/executions/bs.3fd5d8830650b36a

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/test/internal/util/Checks;
     FATAL EXCEPTION: main
Process: io.grpc.android.integrationtest.test, PID: 7998
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/test/internal/util/Checks;
	at androidx.test.core.app.InstrumentationActivityInvoker$BootstrapActivity.onResume(InstrumentationActivityInvoker.java:169)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
	at android.app.Activity.performResume(Activity.java:7939)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.test.internal.util.Checks" on path: DexPathList[[zip file "/data/app/io.grpc.android.integrationtest.test-DYFaHrF4uMZvkQrJs3ID6A==/base.apk"],nativeLibraryDirectories=[/data/app/io.grpc.android.integrationtest.test-DYFaHrF4uMZvkQrJs3ID6A==/lib/arm64, /system/lib64, /system/product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 15 more
```
