### ISSUE TITLE
Getting error error: cannot find symbol private static final com.google.protobuf.Internal.IntListAdapter.IntConverter

### ISSUE THREAD

**Issue by SatyamGondhale** [grpc/grpc-java#11948]
I am getting the above error after updating com.google.protobuf:protoc version from 4.27.5 to 4.28.0. What dependency should I check to fix this or what needs changes in .proto files

**Comment by kannanjgithub** [comment]
The class you mentioned is [there](https://github.com/protocolbuffers/protobuf/blob/439c42c735ae1efed57ab7771986f2a3c0b99319/java/core/src/main/java/com/google/protobuf/Internal.java#L381) in protoc 28.0. Can you provide more details how you arrived at the error?

**Comment by panchenko** [comment]
Seems like a duplicate of #11925

**Comment by kannanjgithub** [comment]
Will wait for the filer to confirm.

**Comment by kannanjgithub** [comment]
I hope your issue is resolved. Feel free to comment to reopen in the future if needed.
